version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
