- name: Configure Firewall Rules in Azure
  hosts: localhost
  tasks:
    - name: Create Firewall Rule
      azure_rm_securitygroup:
        resource_group: "MyResourceGroup"
        name: "MyNSG"
        rules:
          - name: "AllowHTTP"
            protocol: "Tcp"
            direction: "Inbound"
            priority: 200
            source_port_range: "*"
            destination_port_range: "80"
            access: "Allow"
