- name: Configure Docker on VM
  hosts: mydockervm
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Run Nginx Container
      docker_container:
        name: nginx_container
        image: nginx
        state: started
        ports:
          - "80:80"
