- name: Configure Virtual Machine
  hosts: myterraformvm
  become: yes
  tasks:
    - name: Install Apache Web Server
      apt:
        name: apache2
        state: present

    - name: Enable and start Apache service
      systemd:
        name: apache2
        enabled: yes
        state: started
