- name: Configure DNS settings in Azure
  hosts: localhost
  tasks:
    - name: Set DNS servers
      azure_rm_virtualnetwork:
        name: "MyVNET"
        resource_group: "MyResourceGroup"
        dns_servers:
          - "8.8.8.8"
          - "8.8.4.4"
