- name: Configure FortiGate Firewall Rules
  hosts: fortigate
  gather_facts: no
  tasks:
    - name: Create Firewall Rule
      fortinet.fortios.fortios_firewall_policy:
        vdom: "root"
        state: "present"
        firewall_policy:
          policyid: 1
          srcintf: "port1"
          dstintf: "port2"
          srcaddr: "all"
          dstaddr: "all"
          action: "accept"
          schedule: "always"
          service: "ALL"
          logtraffic: "all"
