- name: Create an Azure Virtual Machine
  hosts: localhost
  tasks:
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "MyResourceGroup"
        name: "MyVM"
        vm_size: "Standard_B1s"
        admin_username: "adminuser"
        admin_password: "SecurePass123!"
        image:
          offer: "UbuntuServer"
          publisher: "Canonical"
          sku: "18.04-LTS"
          version: "latest"
